CREATE TABLE IF NOT EXISTS {project_id}.{dataset_id}.{table_name}(
    [id_SK] INT64 PRIMARY KEY AUTOGENERATED,
    [id_NK] INT64,
    parent_id INT64,
    owner_user_id INT64,
    body STRING,
    comment_count INT64,
    creation_date TIMESTAMP,
    last_activity_date TIMESTAMP,
    score INT64,
    uuid STRING,
    ingestion_date DATE
);
