cred_json = 'velvety-ring-349218-f9ffa94dc6a5.json'
project_id = 'velvety-ring-349218'
dataset_id = 'Stack_Overflow'
#table_name = 'staging_data'
table_name = 'staging_data1'
dataset_id = 'Stack_Overflow'
folder_id = '1KDmKD807Tlxdr2m-Kls4UFoO0oicO0th'
queries = '/Users/izabellamartirosyan/Desktop/Capstone/queries'